### ISSUE TITLE
ScrollableView in combination with pull to refresh crashes on Android

### ISSUE THREAD

**Issue by yhanssens** [FokkeZB/nl.fokkezb.pullToRefresh#32]
In my app I have a ScrollableView with three pages. Each of those pages contain a TableView which you can pull to refresh. This works perfectly on iOS unfortunately when I switch pages a couple of times on Android it always seems to crash.

**Comment by dzHamid** [comment]
I have the same issue Mr @FokkeZB. Any solution please !

**Comment by joertler** [comment]
I solved my problem by not using this widget anymore but instead use the module Fokke uses in his widget: https://github.com/raymondkam/Ti.SwipeRefreshLayout directly. Then there shouldn't be a problem :-)

**Comment by dzHamid** [comment]
thank you @joertler 💃
