### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by mohammad19991** [FokkeZB/nl.fokkezb.pullToRefresh#35]
Exception occurred at ti:/module.js:280: Uncaught Error: Requested module not found: com.rkam.swiperefreshlayout.
This happened only on Android.

**Comment by FokkeZB** [comment]
As explained, you need the module it depends on for Android:
https://github.com/FokkeZB/nl.fokkezb.pullToRefresh#usage-

**Comment by mohammad19991** [comment]
thank you I just read that :)
sorry my mistake.
