### ISSUE TITLE
how do i use pull to refresh along with infinite scroll together in a single table view...

### ISSUE THREAD

**Issue by hardikamal** [FokkeZB/nl.fokkezb.pullToRefresh#36]

**Comment by FokkeZB** [comment]
Please provide some more information and code examples.

**Comment by hardikamal** [comment]
I have not started with coding...just wanted to know whether is it possible to use both of them together. For eg. load new data with pull-to-refresh and past data with infinite scroll as in facebook app

**Comment by FokkeZB** [comment]
Yes, they can work together.

**Comment by hardikamal** [comment]
any sample code do u have using both your widgets together??

**Comment by FokkeZB** [comment]
No, I'm sorry. Just follow both of them quick starts and you should be good.

**Comment by hardikamal** [comment]
Thanks bro
