### ISSUE TITLE
Using this with a backbone Collection ?

### ISSUE THREAD

**Issue by nubu** [FokkeZB/nl.fokkezb.pullToRefresh#38]
Hey,
i really wanna use this widget in my project. Is it possible to assign a "normal" Collection (just available in the view corresponding controller) to the list as a dataprovider?

"normal" i mean not available on the global alloy space or/and created through Alloy.createCollec.... ?

Best, nico

**Comment by FokkeZB** [comment]
Sure. The widget only manages the pull to refresh action, sending an event when it is triggered, leaving it to you where you get the data from.
