### ISSUE TITLE
For unknown reason, listView wasn't the first child element, but the second, even though there was only one,

### ISSUE THREAD

**Issue by Topener** [FokkeZB/nl.fokkezb.pullToRefresh#44]
The widget didn't detect my listView because it came in 2nd. The first child was the template. Might have something to do with the `<require>`

My code:

```xml
			<Widget id="ptr" src="nl.fokkezb.pullToRefresh" onRelease="updateStation">
				
				<ListView defaultItemTemplate="departure" onItemclick="itemClick">
					
					<Templates>
						<Require src="Departure"></Require>
					</Templates>
					
					<ListSection
						dataCollection="departures"
						dataTransform="parseDeparture"
						dataFunction="refreshListView"
						>
					</ListSection>
					
				</ListView>
			</Widget>
```

I adjusted the widget in my case. Perhaps a proper change would be to loop through the child elements, find the first ListItem/TableView and attach itself to that?

ps: my listItem is missing here for example sake ;)

**Comment by Dwa1n** [comment]
@Topener If the issue persists can you update your widget with the master branch. I submitted a PR for this exact issue 8 days ago which was accepted :+1:

**Comment by FokkeZB** [comment]
Updated NPM version and GitHub release to 2.1.1
