### ISSUE TITLE
Widget disappear in scrollableview

### ISSUE THREAD

**Issue by jmosqueda1987** [FokkeZB/nl.fokkezb.pullToRefresh#46]
Hi, can you help me, when i have the widget in a scrollable view with other views, this dissappear, You know how it could solve? 

Thanks Regards

**Comment by FokkeZB** [comment]
It only works for table view and list view. Do you have a code example?

**Comment by jmosqueda1987** [comment]
Sure, this is my code example


<ScrollableView class="view" id="viewContainer">
       <View class="container1">
		<TextField id="buscar" class="w-size"></TextField>
		
		<Widget id="ptr" src="nl.fokkezb.pullToRefresh" onRelease="myRefresher">
			<TableView id="ultimas"></TableView>
		</Widget>
	</View>

      <View class="container1">
		<TextField id="buscar" class="w-size"></TextField>
		
		<Widget id="ptr2" src="nl.fokkezb.pullToRefresh" onRelease="myRefresher2">
			<TableView id="ultimas2"></TableView>
		</Widget>
	</View>
</ScrollableView>


When i have one view it works, but with two views the first view dissapear

Thanks for the answer

Regards

**Comment by FokkeZB** [comment]
Is this on iOS or Android?

**Comment by jmosqueda1987** [comment]
I've only tested on Android, in iOS still I am to try it, regards

**Comment by FokkeZB** [comment]
I think it's a issue with the [module](http://gitt.io/component/com.rkam.swiperefreshlayout). Please try to reproduce the issue without the widget (or Alloy - so just plain classic Titanium) and if it still exists, report it at the repo of the module instead. If it does seem like a widget but, please reopen.

**Comment by jmosqueda1987** [comment]
Hi,

With the classic code works but how I can do the callback to refresh the control, here is my code

```javascript
var ptr = Alloy.createWidget("nl.fokkezb.pullToRefresh", {
		id : "ptr",
		children : [tableview]
	}).getView();
	
	ptr.addEventListener("onRelease",function(e){
		alert("");
	});
``` 

Regards

**Comment by FokkeZB** [comment]
Alloy controllers (and those of widgets) are BackBone event dispatchers so you should use `ptr.on("release", fn)`.
