### ISSUE TITLE
Widget disappear in scrollableview(Re-open)

### ISSUE THREAD

**Issue by jmosqueda1987** [FokkeZB/nl.fokkezb.pullToRefresh#47]
Hi,

With the classic code in my controller it works, but how I can do the callback to refresh the control?, here is my code

```javascript
var ptr = Alloy.createWidget("nl.fokkezb.pullToRefresh", {
        id : "ptr",
        children : [tableview]
    }).getView();

    ptr.addEventListener("onRelease",function(e){
        alert("");
    });

```
Thanks
Regards

**Comment by FokkeZB** [comment]
Alloy controllers extend BackBone.Events so the method to call is "on". The event is "release". Please see the Alloy guides, they explain all this.
