### ISSUE TITLE
Widget disappears from table inside scrollview

### ISSUE THREAD

**Issue by ruscles** [FokkeZB/nl.fokkezb.pullToRefresh#49]
I have a table with the widget wrapped around it and both of those are inside a scrollview. When I open a window from that view and then return to the view with the widget, the widget disappears. The widget is working correctly before it disappears. 

```
<Alloy>	
	<View id="standardview">
		<ScrollView id="incidentScrollView" showVerticalScrollIndicator="true">
			<Widget id="ptr" src="nl.fokkezb.pullToRefresh" onRelease="myRefresher">
				<TableView id="incidentTable" backgroundColor="transparent"/>
			</Widget>
		</ScrollView>
	</View>
</Alloy>
```

If I remove the scrollview and just have the widget and table, the widget will refresh as soon as the table is pulled down any distance, it will not refresh onRelease. The widget does not disappear, but it is not working correctly.

```
<Alloy>	
	<View id="standardview">
		<Widget id="ptr" src="nl.fokkezb.pullToRefresh" onRelease="refreshIncidents">
			<TableView id="incidentTable" backgroundColor="transparent"/>
		</Widget>
	</View>
</Alloy>
```

**Comment by ruscles** [comment]
This is only on iOS, neither issue occurs on Android

**Comment by FokkeZB** [comment]
A TableView inside a ScrollView is discouraged. Why would you do that? All that the iOS (latest) version does is enabling http://docs.appcelerator.com/platform/latest/#!/api/Titanium.UI.ListView-property-refreshControl. Do you see the same issue when you do that without the widget?

**Comment by ruscles** [comment]
In order to have the refresh trigger on release (seen below) I have to have the TableView inside the ScrollView. The problem is the widget disappears when I open a window from this view and then return to the view with the widget.
![ios simulator screen shot sep 8 2015 8 49 18 am](https://cloud.githubusercontent.com/assets/11840925/9735172/d4c06364-5606-11e5-8ace-1eb8c0db66c3.png)

If I have just the TableView, the refresh is triggered as soon as the table is pulled down any distance - not when I pull and release the table. (seen below)
![ios simulator screen shot sep 8 2015 8 47 17 am](https://cloud.githubusercontent.com/assets/11840925/9735204/0f562cc0-5607-11e5-9c39-18c8ddcda704.png)

**Comment by FokkeZB** [comment]
You really shouldn't need to wrap it in a ScrollView. It will only make things worse :)

Again, the refreshControl is simply that of Apple, out of the box - no changes. So if you can make a test case (preferably in classic, without the widget) reproducing that what you see (make a video) is not expected behaviour, please create a ticket at jira.appcelerator.org to report it as a bug.
