### ISSUE TITLE
can you tell me how to create this widget in controller file  

### ISSUE THREAD

**Issue by JasonHM** [FokkeZB/nl.fokkezb.pullToRefresh#50]
I want to create `nl.fokkezb.pullToRefresh` in controller(js file),can you have a example to tell me how to create this widgets in js file.
thanks !

**Comment by FokkeZB** [comment]
I don't get your question.

**Comment by JasonHM** [comment]
I had try this widget in view(xml file) good .

**Comment by FokkeZB** [comment]
Ah, OK:

```
Alloy.createWidget('nl.fokkezb.pullToRefresh', {
  children: [$.yourList]
}).on('release', yourCallback);
```
