### ISSUE TITLE
Nice to have: Example without models/collections but normal payloads

### ISSUE THREAD

**Issue by nuno** [FokkeZB/nl.fokkezb.pullToRefresh#54]
Really nice to have a example or sample  without models/collections but normal payloads, special with ListView api.

**Comment by FokkeZB** [comment]
That would be something like:

```
function myRefresher(e) {
    myCollection.sections[0].setItems([
      { info: text: 'Carrot' },
      { info: text: 'Patata' }
    ]);
}
```

**Comment by nuno** [comment]
Sorry my bad, I did a confusion with your great:  https://github.com/FokkeZB/nl.fokkezb.infiniteScroll
