### ISSUE TITLE
Failed to run dexer:

### ISSUE THREAD

**Issue by alexyellowcube** [FokkeZB/nl.fokkezb.pullToRefresh#55]
I get these error while compile the project after add the Ti.SwipeRefreshLayout module to my project. 

[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompatIcs;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionImpl;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoIcsImpl;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompatJellyBeanMr2;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoJellyBeanMr2;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoStubImpl;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/print/PrintHelper;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/print/PrintHelper$PrintHelperStubImpl;

**Comment by FokkeZB** [comment]
Please report module issues at https://github.com/iskugor/Ti.SwipeRefreshLayout
