### ISSUE TITLE
Make the widget a child instead of a parent of the ListView/TableView

### ISSUE THREAD

**Issue by Topener** [FokkeZB/nl.fokkezb.pullToRefresh#56]
Because the widget is a parent, it is impossible to disable it ad-hoc, especially platform specific. 

Reason for this ticket, I want to disable it for Windows Phone, but not for Android and iOS

So this would be great:

```
<ListView>
    <Widget src="nl.fokkezb.pullToRefresh" platform="android,ios />
</ListView>
```

Instead of 

```
<Widget src="nl.fokkezb.pullToRefresh" />
     <ListView>
     </ListView>
</Widget>
```

because in the 2nd/current option it is not possible to disable it platform specific

**Comment by FokkeZB** [comment]
It was a child before, but because of how the Android versions works it needs to be the parent. I think I can still fix #57 though.
