### ISSUE TITLE
Accordion tableView on 3 lavel 

### ISSUE THREAD

**Issue by midoajax** [FokkeZB/nl.fokkezb.pullToRefresh#58]
I have same problem in my code Titanium Alloy to create  Accordion tableView, i m new student and i have end of studies project to finish my study. see attach files 
![accordiontableview](https://cloud.githubusercontent.com/assets/13999668/15616728/832e68c4-243d-11e6-9dc2-1318b9ee6fc3.jpg)

**Comment by nuno** [comment]
Are you sure this the correct repo @midoajax ?

**Comment by FokkeZB** [comment]
@midoajax I don't see any pulltorefresh usage? Closing..
