### ISSUE TITLE
Create this widget programatically

### ISSUE THREAD

**Issue by annamf** [FokkeZB/nl.fokkezb.pullToRefresh#59]
I have to create the widget programatically but I can't add the table view like a child of the widget because it isn't a view. Is this possible? 

My code is:

		var ptr = Alloy.createWidget("nl.fokkezb.pullToRefresh", {
			onRelease: myRefresher()
		});

		var table = Ti.UI.createTableView({
		  id: ('table' + i),
		  data: tableData,
		  separatorStyle: OS_ANDROID ? Ti.UI.TABLE_VIEW_SEPARATOR_STYLE_NONE : Ti.UI.iPhone.TableViewSeparatorStyle.NONE,
		  headerView: header.getView()
		});
		ptr.add(table); // This crashes

**Comment by FokkeZB** [comment]
Hi @annamf,

It's not officially supported, but as Alloy will pass children views as `$.args.children` and the widget [expects this argument](https://github.com/FokkeZB/nl.fokkezb.pullToRefresh/blob/master/nl.fokkezb.pullToRefresh/controllers/widget.js#L16-L18) you could try:

```
var ptr = Alloy.createWidget('nl.fokkezb.pullToRefresh', {
  children: [table]
});

ptr.on('release', myRefresher);
```
