### ISSUE TITLE
Is it possible to disable the pull to refresh?

### ISSUE THREAD

**Issue by icecandy** [FokkeZB/nl.fokkezb.pullToRefresh#60]
I am trying to work out a method to disable the pull-to-refresh.
So one sets it up and uses it and at a later date one wants to disable it. On Android this mainly means that the pull down spinner does not show. All other functionality of the embedded ListView, say, to carry on.
Is this possible?

**Comment by FokkeZB** [comment]
Though not documented, it seems that the Android module this widget uses has a [enable/disable method](https://github.com/iskugor/Ti.SwipeRefreshLayout/blob/master/src/com/rkam/swiperefreshlayout/SwipeRefresh.java#L98).

But, currently the widget [doesn't expose](https://github.com/FokkeZB/nl.fokkezb.pullToRefresh/blob/master/nl.fokkezb.pullToRefresh/controllers/widget.js#L1) the instance of the module for you to call this method. I'll do an update to do that so you can try.

**Comment by icecandy** [comment]
That would be fantastic Fokke.

**Comment by FokkeZB** [comment]
I just published. You can now do:

```
$.ptrWidget.getControl().setEnabled(false);
```

**Comment by icecandy** [comment]
Hi Fokke. Thanks for pointing out the setEnabled function. I did have a look at the Java but didn't see that, but maybe was looking at the wrong fork ie not the most up to date.

**Comment by FokkeZB** [comment]
I found it here:

https://github.com/iskugor/Ti.SwipeRefreshLayout/blob/master/src/com/rkam/swiperefreshlayout/SwipeRefresh.java#L98

Did it work?

**Comment by icecandy** [comment]
I haven't downloaded your updated widget as I have may own modifications already. But the exposed setEnabled definitely works on Android so that's great and thanks for the pointer. On iOS one can disable by assigning list.refreshControl = null. Plus also removing events.

**Comment by FokkeZB** [comment]
OK, closing as fixed then. Thanks!
