### ISSUE TITLE
Uncaught Error in Android 6.0.1

### ISSUE THREAD

**Issue by riveraser** [FokkeZB/nl.fokkezb.pullToRefresh#63]
![screenshot_20160713-154834](https://cloud.githubusercontent.com/assets/9339404/16819426/06036378-4912-11e6-818d-98537a410f2f.png)

Hi there, I got this issue when trying on my phone... I use Titanium SDK 5.2.0  /// Funny thing is that this works perfectly on my emulators..

This is my code:

> ```
>   <Widget id="ptr" src="nl.fokkezb.pullToRefresh" onRelease="myRefresher">
>         <ListView id="listView" defaultItemTemplate="template" onItemclick="onItemClick">
>             <Templates>
>                     <ItemTemplate name="template" class="itemContenedor" >
>                         <View>
>                             <ImageView bindId="imgNota" class="imagenLista" defaultImage="/images/imgDefault.jpg"  />
>                         </View>
>                         <View class="contenedorTitulo" >
>                             <Label bindId="title" id="title" /> 
>                         </View>
>                     </ItemTemplate>
>                 </Templates>
> ```

```
                <Widget id="listWidgetNotas" src="nl.fokkezb.infiniteScroll" onEnd="listLoader" />
                <ListSection id="section" dataCollection="notasHome" >
                    <ListItem notaid:id="{id}" title:text="{titulonota}" imgNota:image="{imageintro}" />
                </ListSection>
            </ListView>
        </Widget>
```

**Comment by riveraser** [comment]
<Widget id="ptr" src="nl.fokkezb.pullToRefresh" onRelease="myRefresher">
			<ListView id="listView" defaultItemTemplate="template" onItemclick="onItemClick">

<Templates>
		                <ItemTemplate name="template" class="itemContenedor" >
		                    <View>
		                    	<ImageView bindId="imgNota" class="imagenLista" defaultImage="/images/imgDefault.jpg"  />
		                    </View>
		                    <View class="contenedorTitulo" >
		                    	<Label bindId="title" id="title" /> 
		                   	</View>
		                </ItemTemplate>
		            </Templates>
		            
		            <Widget id="listWidgetNotas" src="nl.fokkezb.infiniteScroll" onEnd="listLoader" />
		            <ListSection id="section" dataCollection="notasHome" >
		                <ListItem notaid:id="{id}" title:text="{titulonota}" imgNota:image="{imageintro}" />
		            </ListSection>
		        </ListView>
	        </Widget>

**Comment by FokkeZB** [comment]
The widget should wrap the ListView, not be a child of it. Please follow the steps in the readme:

https://github.com/FokkeZB/nl.fokkezb.pullToRefresh#usage

**Comment by riveraser** [comment]
Widget is the main element and the listview is inside the widget as you can see in the code I pasted..

<widget pullToRefresh>
   <listview>....
   </listview>
</widget>

Maybe you saw the Infiniti Scroller widget inside the list view....

**Comment by FokkeZB** [comment]
Sorry, indeed.

I've never seen this error before. It seems to be related to the `setRefreshing` code:
https://github.com/FokkeZB/nl.fokkezb.pullToRefresh/blob/master/nl.fokkezb.pullToRefresh/controllers/widget.js#L79-L93

Could you play a little with different devices/emulators, leaving out init functions etc to see if you can narrow down perhaps?

**Comment by FokkeZB** [comment]
It looks like an error in the [module](http://gitt.io/component/com.rkam.swiperefreshlayout). Could you try without the widget (following the instructions of the module) and report it there?

**Comment by Topener** [comment]
@riveraser have you tried @FokkeZB's comment?

**Comment by fnando521** [comment]
The error occurs in widget.js:

refreshControl.setRefreshing(false);

Commenting this line out no longer causes the error, however, the loading indicator is never dimissed

**Comment by FokkeZB** [comment]
That seems like a module issue then. It could also depend on the module for you are using. I originally made it to work with https://github.com/iskugor/Ti.SwipeRefreshLayout#set-refreshing but some people also use e.g. http://gitt.io/component/com.rkam.swiperefreshlayout. 

Please play around with these module forks and report the bug at the relevant repo if neither of them work.

**Comment by hansemannn** [comment]
Fixed it, the issue was related to the UI-thread.

**Comment by FokkeZB** [comment]
![](http://media3.giphy.com/media/l0MYKO0EWhuiZQ2RO/200w.gif)
