### ISSUE TITLE
Cannot install new version

### ISSUE THREAD

**Issue by DISUK** [FokkeZB/nl.fokkezb.pullToRefresh#64]
We recently changed the system that we are developing on, and as a result need to re-install the widget. It seems since our last install, the widget has been updated. This new version will not install into Appcelerator. On attempt, we receive the following message:

"Unable to download the module from the specified URL. Is the URL valid?"

Despite our best efforts, we cannot find a work around. We would appreciate any help possible.

Thanks.

**Comment by FokkeZB** [comment]
How do you install the widget?

**Comment by DISUK** [comment]
Help > Install mobile module > Install from URL (paste this URL https://github.com/FokkeZB/nl.fokkezb.pullToRefresh.git) > Error Message "Unable to download the module from the specified URL. Is the URL valid?"

We have also tried to install with Node, but we had a similar error message. It stated that the problem probably did not lie with our end, but with the package installer. 

We have tried this on two different machines, one of which has the previous version.

**Comment by FokkeZB** [comment]
@DISUK, the method you describe is to install Titanium modules, not Alloy widgets. Alloy widgets don't have any official (automated) install method.

See the docs: http://docs.appcelerator.com/platform/latest/#!/guide/Alloy_XML_Markup-section-46248608_AlloyXMLMarkup-ImportingWidgets

This particular widget is also available via gitT.io.

See the readme: https://github.com/FokkeZB/nl.fokkezb.pullToRefresh#usage
