### ISSUE TITLE
How to Integrate Pull to refresh and Infinite Scroll Widget in Single List or table View

### ISSUE THREAD

**Issue by ibudhiraja** [FokkeZB/nl.fokkezb.pullToRefresh#65]
Hi Fokke,

I have tried to integrate both of your widgets in single ListView and also in table view. but not able to integrate successfully. After using both widgets either app got crashed or data on list view is not visible. Can you please help me in this scenario or give the example code. 

Thanks

**Comment by FokkeZB** [comment]
Closing in favour of https://github.com/FokkeZB/nl.fokkezb.infiniteScroll/issues/59
