### ISSUE TITLE
Use in Appcelerator Corporate Directory Example

### ISSUE THREAD

**Issue by safadig** [FokkeZB/nl.fokkezb.pullToRefresh#69]
Thanks for a great Widget
Having difficulty implementing in Directory Example ( No Model/Collection) .Not sure if it is the way I am calling the myRefresher function?

directory.xml

```xml
<Widget id="ptr" src="nl.fokkezb.pullToRefresh" onRelease="myRefresher">
		<ListView id="listView" defaultItemTemplate="userTemplate">
			<Templates>
				/////
			</Templates>
				</ListView>
		</Widget>
	</Window>
```

directory.js

```js
function myRefresher(e) {
         success: init;
         error: e.hide;
    }

$.ptr.refresh();
```

**Comment by FokkeZB** [comment]
In `myRefresher()` you should do whatever you want to do to refresh the data in your listView and when you're done call `e.hide()`.

**Comment by ikalangita** [comment]
Hi, i tried and works great, but i have an issue, when pull my data is calling twice and listview content is duplicated, could you help me please? thank you.

**Comment by Topener** [comment]
Please join www.tislack.org and ask help there. Or Stackoverflow and use the `appcelerator` tag.
