### ISSUE TITLE
Tableview with Swipe event does not trigger refreshstart event directly

### ISSUE THREAD

**Issue by ramonthegreat** [FokkeZB/nl.fokkezb.pullToRefresh#76]
I integrated pullToRefresh widget with TableView, unfortunately when I add a Swipe event to tableview, the refreshstart event of RefreshControl does not trigger directly.

OS: Android 7
TiSDK: 7.1.0

For the record, I modified the widget.js by removing the if else(OS_IOS and OS_ANDROID) condition since RefreshControl is already available on Android platform.

**Comment by Topener** [comment]
There is no need to use this widget with TiSDK 7.1.0. It is natively build in since 6.2.0 as you can see in the description. The widget basically does nothing anymore and only makes your app more complicated ;) I recommend sticking to the regular flow.
